---

- name: Copia de arquivos
  hosts: all
  tasks:
    - name: COPY {{origem}}  >>> {{destino}}
      ansible.builtin.win_copy:
        src: '{{origem}}'
        dest: '{{destino}}'
        remote_src: true
...



